### ISSUE TITLE
Error opening document with word processor when GeSHi  language is specified in <code> tag

### ISSUE THREAD

**Issue by spricer** [lpaulsen93/dokuwiki-plugin-odt#311]
Exported document throws error during openings when GeSHi language is specified in ``<code>`` tag.
Can be reproduced with simple entry:
```
<code PowerShell>
DEMO
</code>
```

**Comment by eduardomozart** [comment]
Can you please share your bookcreator plugin settings (print screen) and the pages structure (as seem in ``data/`` directory on your DokuWiki instance) used to generate those pages?

**Comment by eduardomozart** [comment]
Hello,
I was able to open it without any issues on 7.6.4.1. Which LibreOffice version you're using? Were you able to generate those on older ODT plugin versions? The PHP 8 migration of this plugin wasn't as top of notch as it should, I did the best I could, but as I work on it as a side project (just because it's a plugin I use), maybe an older ODT version (2019) works better for you and we work from it to attempt to fix it.
Please notice that Word and other programs issues probably will not be handled here because ODT format are a LibreOffice/OpenOffice native format and issues may occur on outside programs when converting them.

**Comment by spricer** [comment]
True, opening this in LO doesn't throw error so I guess nothing to be done here. Will close Issue
